DROP SEQUENCE city_id_seq;
DROP SEQUENCE program_id_seq;

DROP TRIGGER Order_Friend_Pairs;
DROP TRIGGER city_id_trigger;
DROP TRIGGER program_id_trigger;

DROP TABLE Tags CASCADE CONSTRAINTS;
DROP TABLE Photos CASCADE CONSTRAINTS;
DROP TABLE Albums CASCADE CONSTRAINTS;
DROP TABLE Participants CASCADE CONSTRAINTS;
DROP TABLE User_Events CASCADE CONSTRAINTS;
DROP TABLE Education CASCADE CONSTRAINTS;
DROP TABLE Programs CASCADE CONSTRAINTS;
DROP TABLE Messages CASCADE CONSTRAINTS;
DROP TABLE User_Hometown_Cities CASCADE CONSTRAINTS;
DROP TABLE User_Current_Cities CASCADE CONSTRAINTS;
DROP TABLE Cities CASCADE CONSTRAINTS;
DROP TABLE Friends CASCADE CONSTRAINTS;
DROP TABLE Users CASCADE CONSTRAINTS;